### ISSUE TITLE
[Feature suggestion]

### ISSUE THREAD

**Issue by augustobob** [Burrit0z/Cartella-Bug-Tracker#2]
In grid configuration the sliders to set the top+bottom offset should be independent and all slides need to go from -100 to +100, as I needed to set manually the plist to fit my screen.
The option to resize the folder icon worked flawlessly to fit my icons inside my folder icon, thx.

**Expected behavior**

**Screenshots**
![19EDE2ED-58C9-4F4A-B7B1-DE21610C7866](https://user-images.githubusercontent.com/41238825/75097541-a62c7280-558a-11ea-80ac-7107c32ba32f.png)
.
With the limited sliders all the icons overlap each other’s 
**iOS Version:** 13.3.1

**iPhone Model:** 7 plus 

**Additional context**
I use my device with the resolution changed to 2496x1405 and not everything fits correctly, btw Your tweak worked fine, just the offsets mentioned needed to be manually changed.

**Comment by Burrit0z** [comment]
Sure. I will do so.
